### ISSUE TITLE
Sidekiq::Batch::Empty ignores the default queue setting while scheduling

### ISSUE THREAD

**Issue by RemcodM** [sidekiq/sidekiq#5916] opened 2023-05-12 09:21 UTC
Ruby version: 3.1.4
Rails version: 7.0.4.3
Sidekiq / Pro / Enterprise version(s):
 - `sidekiq`: 7.1.0
 - `sidekiq-pro`: 7.1.1
 - `sidekiq-ent`: 7.1.0

I have included what I think are the relevant parts of our initializer, since otherwise it would be a lot:
```
Sidekiq.default_job_options = { 'retry' => 0, 'backtrace' => false, 'queue' => 'mb2' }
```

`sidekiq.yml`:
```
# Sidekiq configuration used by the default job workers in production.
:concurrency: 10
:queues:
  - [mb2_synchronization, 7]
  - [email_fetcher, 6]
  - [mb2, 5]
  - [mb2_background, 4]
  - [mb2_eventually, 3]
  - [mb2_auto_link_financial_mutation_jobs, 3]
  - [mb2_subgoal_jobs, 3]
  - [elasticsearch, 2]
  - [event_tracking, 1]
```

Since Sidekiq Pro 7.1, empty batches will now generate a `Sidekiq::Batch::Empty` job to run callbacks. However, we noticed last night that this job seems to ignore our default queue setting.

Per our `sidekiq.rb`, the default queue for jobs is `mb2`. However, the `Sidekiq::Batch::Empty` seems to be queued on the `default` queue regardless of this setting. We also think this is non-configurable.

Would it be possible to schedule this on the default queue as setup in the initializer?

**Comment by mperham** [comment] 2023-05-12 17:02
Dupe of #5914

**Closed by mperham** 2023-05-12 17:02 UTC
