### ISSUE TITLE
Rack::Lint::LintError: uppercase character in header name: Cache-Control (Rack::Lint::LintError)

### ISSUE THREAD

**Issue by espen** [sidekiq/sidekiq#6012] opened 2023-08-28 10:24 UTC
Ruby version: 3.2.2
Rails version: n/a
Sidekiq / Pro / Enterprise version(s): 7.1.2

All assets returns 500 in Rack:
```
127.0.0.1 - - [28/Aug/2023:12:07:57 +0200] "GET /stylesheets/application-dark.css HTTP/1.1" 500 63469 0.0278
Rack::Lint::LintError: uppercase character in header name: Cache-Control (Rack::Lint::LintError)
  gems/rack-3.0.7/lib/rack/lint.rb:653:in `block in check_headers'
  gems/rack-3.0.7/lib/rack/lint.rb:637:in `each'
  gems/rack-3.0.7/lib/rack/lint.rb:637:in `check_headers'
  gems/rack-3.0.7/lib/rack/lint.rb:73:in `response'
  gems/rack-3.0.7/lib/rack/lint.rb:35:in `call'
  gems/rack-3.0.7/lib/rack/show_exceptions.rb:27:in `call'
  gems/rack-3.0.7/lib/rack/common_logger.rb:43:in `call'
  gems/rack-3.0.7/lib/rack/content_length.rb:20:in `call'
  gems/rackup-2.1.0/lib/rackup/handler/webrick.rb:111:in `service'
  gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
  gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
  gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
```

This works on Sidekiq 7.1.1.

Using Rack, Rackup and Webrick.

Rack enforces lower-case headers. See https://github.com/rack/rack/issues/1592 and https://github.com/rack/rack/pull/1812

I don't know why this wasn't an issue before as only the cache header value was changed here: https://github.com/sidekiq/sidekiq/commit/5681a5d5cfeb037e2703cc3850ad5f394236d4ec

**Comment by mperham** [comment] 2023-08-28 14:39
Dupe of #5951

**Closed by mperham** 2023-08-28 14:39 UTC

**Comment by espen** [comment] 2023-08-29 10:10
Thanks. Sorry, I really thought I did a proper search for this.
