### ISSUE TITLE
Frequent ReadTimeouts to Redis for Limiters started to appear after upgrading to sidekiq 7 and redis 5

### ISSUE THREAD

**Issue by NielsKSchjoedt** [sidekiq/sidekiq#5857] opened 2023-03-29 08:03 UTC
Ruby version: 2.7.7
Rails version: 6.1
Sidekiq / Pro / Enterprise version(s):
7.0.7 / 7.0.6 / 7.0.8

After upgrading from sidekiq 6.5 and redis 4.8 to 5.0 I am starting to see frequent ReadTimeout errors from Redis on sidekiq connections for limiters. I have not changed behaviour or usage of limiters and I have not changed redis configurations.

```
RedisClient::ReadTimeoutError: RedisClient::ReadTimeoutError
```
![Skærmbillede 2023-03-29 kl  10 00 03](https://user-images.githubusercontent.com/570755/228466845-12a06c99-1c02-44d8-ba10-43f053996862.png)

```ruby
# initializers/sidekiq.rb
Sidekiq::Limiter.configure do |config|
  config.redis = REDIS_RATE_LIMIT
end
```

**Comment by mperham** [comment] 2023-03-29 16:50
Enterprise 7.0.7 is out with a fix. Can you `bundle up sidekiq-ent` and, if you see the error again, please supply the full backtrace text?

**Comment by 97jaz** [comment] 2023-03-29 19:57
We're also getting this error. Just updated to the latest `sidekiq-ent`, and we're still getting it, though less frequently. Full stacktrace:
```
redis-client (0.14.0) lib/redis_client/ruby_connection/buffered_io.rb:140 block in fill_buffer |  
redis-client (0.14.0) lib/redis_client/ruby_connection/buffered_io.rb:122 loop |  
redis-client (0.14.0) lib/redis_client/ruby_connection/buffered_io.rb:122 fill_buffer |  
redis-client (0.14.0) lib/redis_client/ruby_connection/buffered_io.rb:114 ensure_remaining |  
redis-client (0.14.0) lib/redis_client/ruby_connection/buffered_io.rb:85 getbyte |  
redis-client (0.14.0) lib/redis_client/ruby_connection/resp3.rb:113 parse |  
redis-client (0.14.0) lib/redis_client/ruby_connection/resp3.rb:50 load |  
redis-client (0.14.0) lib/redis_client/ruby_connection.rb:96 block in read |  
redis-client (0.14.0) lib/redis_client/ruby_connection/buffered_io.rb:48 with_timeout |  
redis-client (0.14.0) lib/redis_client/ruby_connection.rb:96 read |  
redis-client (0.14.0) lib/redis_client/connection_mixin.rb:31 call |  
redis-client (0.14.0) lib/redis_client.rb:272 block (2 levels) in blocking_call |  
redis-client (0.14.0) lib/redis_client/middlewares.rb:16 call |  
redis-client (0.14.0) lib/redis_client.rb:271 block in blocking_call |  
redis-client (0.14.0) lib/redis_client.rb:626 ensure_connected |  
redis-client (0.14.0) lib/redis_client.rb:270 blocking_call |  
redis-client (0.14.0) lib/redis_client/decorator.rb:26 blocking_call |  
sidekiq-ent (7.0.7) lib/sidekiq-ent/limiter/concurrent.rb:199 block in lock |  
sidekiq-ent (7.0.7) lib/sidekiq-ent/limiter.rb:92 block in redis |  
lib/connection_pool.rb:107 block (2 levels) in with |  
lib/connection_pool.rb:106 handle_interrupt |  
lib/connection_pool.rb:106 block in with |  
lib/connection_pool.rb:103 handle_interrupt |  
lib/connection_pool.rb:103 with |  
sidekiq-ent (7.0.7) lib/sidekiq-ent/limiter.rb:89 redis |  
sidekiq-ent (7.0.7) lib/sidekiq-ent/limiter/concurrent.rb:194 lock |  
sidekiq-ent (7.0.7) lib/sidekiq-ent/limiter/concurrent.rb:61 within_limit |  
app/workers/patient_history_worker.rb:17 perform |  
lib/sidekiq/processor.rb:209 execute_job |  
lib/sidekiq/processor.rb:177 block (2 levels) in process |  
lib/sidekiq/middleware/chain.rb:180 traverse |  
lib/sidekiq/middleware/chain.rb:183 block in traverse |  
lib/sidekiq/middleware/server/influx_metrics_logger.rb:24 call |  
lib/sidekiq/middleware/chain.rb:182 traverse |  
lib/sidekiq/middleware/chain.rb:183 block in traverse |  
sidekiq-pro (7.0.9) lib/sidekiq/batch/middleware.rb:58 call |  
lib/sidekiq/middleware/chain.rb:182 traverse |  
lib/sidekiq/middleware/chain.rb:183 block in traverse |  
sidekiq-ent (7.0.7) lib/sidekiq-ent/unique.rb:182 call |  
lib/sidekiq/middleware/chain.rb:182 traverse |  
lib/sidekiq/middleware/chain.rb:183 block in traverse |  
sidekiq-ent (7.0.7) lib/sidekiq-ent/limiter/middleware.rb:39 call |  
lib/sidekiq/middleware/chain.rb:182 traverse |  
lib/sidekiq/middleware/chain.rb:183 block in traverse |  
lib/sidekiq/metrics/tracking.rb:26 track |  
lib/sidekiq/metrics/tracking.rb:122 call |  
lib/sidekiq/middleware/chain.rb:182 traverse |  
lib/sidekiq/middleware/chain.rb:183 block in traverse |  
lib/appsignal/integrations/sidekiq.rb:57 block in call |  
lib/appsignal/helpers/instrumentation.rb:528 instrument |  
lib/appsignal/integrations/sidekiq.rb:56 call |  
lib/sidekiq/middleware/chain.rb:182 traverse |  
lib/sidekiq/middleware/chain.rb:173 invoke |  
lib/sidekiq/processor.rb:176 block in process |  
lib/sidekiq/processor.rb:140 block (6 levels) in dispatch |  
lib/sidekiq/job_retry.rb:113 local |  
lib/sidekiq/processor.rb:139 block (5 levels) in dispatch |  
lib/sidekiq/rails.rb:16 block in call |  
lib/active_support/execution_wrapper.rb:92 wrap |  
lib/active_support/reloader.rb:72 block in wrap |  
lib/active_support/execution_wrapper.rb:92 wrap |  
lib/active_support/reloader.rb:71 wrap |  
lib/sidekiq/rails.rb:15 call |  
lib/sidekiq/processor.rb:135 block (4 levels) in dispatch |  
lib/sidekiq/processor.rb:270 stats |  
lib/sidekiq/processor.rb:130 block (3 levels) in dispatch |  
lib/sidekiq/job_logger.rb:13 call |  
lib/sidekiq/processor.rb:129 block (2 levels) in dispatch |  
lib/sidekiq/job_retry.rb:80 global |  
lib/sidekiq/processor.rb:128 block in dispatch |  
lib/sidekiq/job_logger.rb:39 prepare |  
lib/sidekiq/processor.rb:127 dispatch |  
lib/sidekiq/processor.rb:175 process |  
lib/sidekiq/processor.rb:82 process_one |  
lib/sidekiq/processor.rb:72 run |  
lib/sidekiq/component.rb:10 watchdog |  
lib/sidekiq/component.rb:19 block in safe_thread
```

**Comment by mperham** [comment] 2023-03-29 21:18
@casperisfine any ideas on how to debug this further? Can the exception provide anymore context, like the timeout value, eg “timed out after X sec”?

**Comment by casperisfine** [comment] 2023-03-30 07:25
> like the timeout value, eg “timed out after X sec”?

Should be doable yes.

**Comment by mperham** [comment] 2023-04-04 00:01
Can anyone give me a Ruby script which reproduces the behavior? The rate limiter API can be used from any Ruby process, not just Sidekiq. For instance, here's a script which uses the concurrent rate limiter. The comment shows the expected output.

```ruby
require "sidekiq-ent"

=begin
% bundle exec ruby lim.rb
2023-04-03T23:57:27.225Z pid=7291 tid=3yj INFO: Sidekiq 7.0.7 connecting to Redis with options {:size=>10, :pool_name=>"internal", :pool_timeout=>5, :url=>nil}
I, [2023-04-03T16:57:27.229407 #7291]  INFO -- : [2240, "start"]
I, [2023-04-03T16:57:27.231520 #7291]  INFO -- : [2260, "start"]
I, [2023-04-03T16:57:27.231666 #7291]  INFO -- : [2280, "start"]
I, [2023-04-03T16:57:27.232156 #7291]  INFO -- : [2300, "start"]
I, [2023-04-03T16:57:27.232172 #7291]  INFO -- : [2320, "start"]
I, [2023-04-03T16:57:30.234629 #7291]  INFO -- : [2240, "done"]
I, [2023-04-03T16:57:30.236772 #7291]  INFO -- : [2280, "done"]
I, [2023-04-03T16:57:30.237094 #7291]  INFO -- : [2300, "done"]
I, [2023-04-03T16:57:30.237408 #7291]  INFO -- : [2320, "done"]
I, [2023-04-03T16:57:30.236628 #7291]  INFO -- : [2260, "done"]
I, [2023-04-03T16:57:30.237863 #7291]  INFO -- : [2340, "start"]
I, [2023-04-03T16:57:30.238848 #7291]  INFO -- : [2360, "start"]
I, [2023-04-03T16:57:30.239550 #7291]  INFO -- : [2380, "start"]
I, [2023-04-03T16:57:30.239661 #7291]  INFO -- : [2400, "start"]
I, [2023-04-03T16:57:30.239773 #7291]  INFO -- : [2420, "start"]
I, [2023-04-03T16:57:33.241944 #7291]  INFO -- : [2340, "done"]
I, [2023-04-03T16:57:33.243136 #7291]  INFO -- : [2380, "done"]
I, [2023-04-03T16:57:33.243207 #7291]  INFO -- : [2400, "done"]
I, [2023-04-03T16:57:33.243322 #7291]  INFO -- : [2420, "done"]
I, [2023-04-03T16:57:33.243970 #7291]  INFO -- : [2360, "done"]
=end

Sidekiq.configure_client do |cfg|
  cfg.redis = {pool_timeout: 5, size: 10}
end
Sidekiq.redis(&:flushdb)
LOG = ::Logger.new($stdout)

C = Sidekiq::Limiter.concurrent("foo", 5)

ts = (1..10).map do
  Thread.new do
    C.within_limit do
      LOG.info { [Thread.current.object_id, "start"] }
      sleep 3
      LOG.info { [Thread.current.object_id, "done"] }
    end
  rescue => ex
    LOG.error { [Thread.current.object_id, ex.message, ex.class.name] }
  end
end
ts.each(&:join)
```

**Comment by 97jaz** [comment] 2023-04-04 23:20
Another, seemingly related, item: we reverted to sidekiq-ent 7.0.5, but we did not revert sidekiq-pro, and over the past few days we've seen two redis-client timeouts, both from super-fetch. The cases are very similar: waiting on the response after a BRPOPLPUSH. The stack traces are identical down to the point where you're in sidekiq code, rather than redis-client code.

Is it possible that redis just isn't promptly timing out the BRPOPLPUSH? I read over [the old issue](https://github.com/sidekiq/sidekiq/issues/2431) where the redis `hz` config setting was discussed in some detail. It sounds like that was improved in redis a long time ago, but I wonder if this is a similar problem.

I've turned on latency monitoring in our redis server, just in case that turns up anything useful. (We're running redis 7, by the way.)

**Comment by mperham** [comment] 2023-04-05 00:33
I've never seen a bug based on `hz` so I'd doubt that. Two timeouts in a few days isn't much, that's pretty rare and hard to reproduce. This is the only relevant diff with Enterprise v7.0.5:

```diff
-            candidate = conn.blocking_call(false, "brpoplpush", @free, @pend, diff.to_f)
+            candidate = conn.blocking_call(diff + 1, "brpoplpush", @free, @pend, diff.to_f)
```

`false` means no client timeouts at all. Is it possible you are seeing actual client-side timeouts due to your current CPU load and network status?

**Comment by 97jaz** [comment] 2023-04-05 00:59
The `hz` thing isn't exactly a bug, as I understand it. It's just that redis doesn't make strong guarantees about how soon a timeout will actually get noticed after the timeout period has elapsed.

But at any rate, redis is supposedly much better about this than it used to be, from what I gather.

> Is it possible you are seeing actual client-side timeouts due to your current CPU load and network status?

Network status seems particularly unlikely. CPU load on the client isn't impossible. I'll take a look at our monitoring logs.

**Comment by 97jaz** [comment] 2023-04-05 01:26
Hmm... CPU load on the client is very far from impossible. I'll do some experimentation.

**Comment by casperisfine** [comment] 2023-04-05 10:53
> CPU load on the client is very far from impossible.

Yeah, if you use a lot of threads, each can hold the CPU for as long as 100ms, so it's not impossible that on a very busy instance it may cause timeouts such as this one.

**Comment by 97jaz** [comment] 2023-04-05 14:16
The largest number of limiter-related timeouts did, in fact, come from a service that was under-provisioned for CPU. However, we still had limiter timeouts -- not as many, but still too many -- from services that have ample CPU.

I don't think I'm going to be able to recreate these conditions outside of production. It would be useful for me to have a simple way of adjusting, say, the amount of time added to a limiter's `:wait_timeout` when determining the client's timeout. Since the timeouts also occur in other places, not just in limiters, it would be useful to have a lever (or levers) for those cases, as well. I noticed, for example, that the client timeout is hard-coded in super-fetch.

**Comment by casperisfine** [comment] 2023-04-05 14:19
Yeah, that's why I initially suggested to do `conn.blocking_call(diff + conn.read_timeout, ...`

**Comment by mperham** [comment] 2023-04-05 16:10
I'm inclined to call this issue "wont fix". Systems should break like this under load. Timeouts are supposed to indicate an application with poor health and it sounds like that's what is happening here. Chime in if you feel differently.

**Closed by mperham** 2023-04-05 16:10 UTC

**Comment by 97jaz** [comment] 2023-04-05 16:48
Well, like I wrote above, we appear to have seen a good number of timeouts from a service that was not under heavy load. I don't think we've proven anything yet.

**Comment by tiagotex** [comment] 2023-07-21 12:12
We are also seeing this error a few times a week even though the system is not under load, I think the issue is within `lib/sidekiq-ent/limiter/concurrent.rb` lock method:

```ruby
def lock
  start = ::Process.clock_gettime(::Process::CLOCK_MONOTONIC)
  # ...

  Sidekiq::Limiter.redis do |conn|
    wait_until = start + wait_for
    diff = wait_until - ::Process.clock_gettime(::Process::CLOCK_MONOTONIC)
    while diff > 0
      candidate = conn.blocking_call(diff + 1, "BLMOVE", @free, @pend, "RIGHT", "LEFT", diff.to_f)
    
      # ...

      diff = wait_until - ::Process.clock_gettime(::Process::CLOCK_MONOTONIC)
  end

  # ...
end
```

In our app we have configured `network_timeout: 3` and `pool_timeout: 3` to deal with latency spikes in the network. And set our Concurrent limit with a `wait_timeout: 5`

On the first iteration, `wait_until` with be a timestamp 5 seconds in the future and that `diff` is 5 seconds, we call `conn.blocking_call` with a timeout value of 6 seconds.

If there is another iteration, `diff` is could now be 0 and we call  `conn.blocking_call` with a timeout value of 1 second; this is lower than our `network_timeout` and causes us to see the error:

```
RedisClient::ReadTimeoutError: Waited 1.0002597961574793 seconds (RedisClient::ReadTimeoutError)
  from redis-client (0.14.1) lib/redis_client/ruby_connection/buffered_io.rb:140:in `block in fill_buffer'
  from redis-client (0.14.1) lib/redis_client/ruby_connection/buffered_io.rb:122:in `loop'
  from redis-client (0.14.1) lib/redis_client/ruby_connection/buffered_io.rb:122:in `fill_buffer'
  from redis-client (0.14.1) lib/redis_client/ruby_connection/buffered_io.rb:114:in `ensure_remaining'
  from redis-client (0.14.1) lib/redis_client/ruby_connection/buffered_io.rb:85:in `getbyte'
  from redis-client (0.14.1) lib/redis_client/ruby_connection/resp3.rb:113:in `parse'
  from redis-client (0.14.1) lib/redis_client/ruby_connection/resp3.rb:50:in `load'
  from redis-client (0.14.1) lib/redis_client/ruby_connection.rb:96:in `block in read'
  from redis-client (0.14.1) lib/redis_client/ruby_connection/buffered_io.rb:48:in `with_timeout'
  from redis-client (0.14.1) lib/redis_client/ruby_connection.rb:96:in `read'
  from redis-client (0.14.1) lib/redis_client/connection_mixin.rb:31:in `call'
  from redis-client (0.14.1) lib/redis_client.rb:272:in `block (2 levels) in blocking_call'
  from redis-client (0.14.1) lib/redis_client/middlewares.rb:16:in `call'
  from redis-client (0.14.1) lib/redis_client.rb:271:in `block in blocking_call'
  from redis-client (0.14.1) lib/redis_client.rb:626:in `ensure_connected'
  from redis-client (0.14.1) lib/redis_client.rb:270:in `blocking_call'
  from redis-client (0.14.1) lib/redis_client/decorator.rb:26:in `blocking_call'
  from sidekiq-ent (7.1.1) lib/sidekiq-ent/limiter/concurrent.rb:109:in `block in lock'
  from sidekiq-ent (7.1.1) lib/sidekiq-ent/limiter.rb:103:in `block in redis'
  from connection_pool (2.4.1) lib/connection_pool.rb:110:in `block (2 levels) in with'
  from connection_pool (2.4.1) lib/connection_pool.rb:109:in `handle_interrupt'
  from connection_pool (2.4.1) lib/connection_pool.rb:109:in `block in with'
  from connection_pool (2.4.1) lib/connection_pool.rb:106:in `handle_interrupt'
  from connection_pool (2.4.1) lib/connection_pool.rb:106:in `with'
  from sidekiq-ent (7.1.1) lib/sidekiq-ent/limiter.rb:100:in `redis'
  from sidekiq-ent (7.1.1) lib/sidekiq-ent/limiter/concurrent.rb:104:in `lock'
  from sidekiq-ent (7.1.1) lib/sidekiq-ent/limiter/concurrent.rb:61:in `within_limit'
```

@casperisfine suggested adding `read_timeout` to ensure that the timeout is never smaller than the `network_timeout` configured: 

```ruby
conn.blocking_call(diff + conn.read_timeout, ...
```

This makes sense to me since we currently seem to be disregarding the timeout config by using hardcoded `1`.

@mperham Would you be open to changing this to use `read_timeout` instead of `1`?

**Comment by mperham** [comment] 2023-08-19 14:52
I'm not sure. wait_timeout is supposed to be an SLA: you only want to wait for N seconds, not N + read_timeout seconds. So I don't know the right thing to do here: strict or lax?

But also: why is this Redis instance or the network so slow that timeouts of seconds matter? Is this the pain of a system which is struggling to scale or has an underlying performance issue which needs to be solved?
